#**Tutorial-01 Practice**

perceptron class

In [2]:
import numpy as np

class Perceptron(object):

  def __init__(self, eta=0.01, n_iter=10):
    self.eta = eta
    self.n_iter = n_iter

  def weighted_sum(self, X):
    return np.dot(X, self.w_[1:]) + self.w_[0]

  def predict(self, X):
    return np.where(self.weighted_sum(X) >= 0.0, 1, -1)

  def fit(self, X, y):
    self.w_ = np.zeros(1 + X.shape[1])
    self.errors_ = []

    print("weights:", self.w_)
    for _ in range(self.n_iter):
      errors = 0
      for xi, y in zip(X, y):
        y_pred = self.predict(xi)
        update = self.eta * (y - y_pred)
        self.w_[1:] += update * xi
        print("updated weights:", self.w_)
        self.w_[0] += update
        error += int(update != 0.0)
      self.errors_.append(errors)
    return self



testing our perceptron class

In [6]:
import pandas as pd
from sklearn.utils import shuffle
import numpy as np

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
df = shuffle(df)
df.head

X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
print(X[0:5])
print(y[0:5])



[[6.  3.4 4.5 1.6]
 [4.9 3.1 1.5 0.1]
 [5.4 3.  4.5 1.5]
 [5.5 3.5 1.3 0.2]
 [6.1 2.6 5.6 1.4]]
['Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica']


In [8]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.25)

train_labels = np.where(train_labels == 'Iris-setosa', -1, 1)
test_labels = np.where(test_labels == 'Iris-setosa', -1, 1)

print('train data:', train_data[0:2])
print('train labels:', train_labels[0:2])

print('test data:', test_data[0:2])
print('test labels:', test_labels[0:2])


train data: [[6.7 3.3 5.7 2.1]
 [4.9 3.1 1.5 0.1]]
train labels: [ 1 -1]
test data: [[5.  3.  1.6 0.2]
 [5.7 2.5 5.  2. ]]
test labels: [-1  1]


training the perceptron

In [10]:
from sklearn.linear_model import Perceptron

perceptron = Perceptron(eta0=0.1, max_iter=10)
perceptron.fit(train_data, train_labels)

#making predictions on test data
test_preds = perceptron.predict(test_data)
print(test_preds)

[-1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1  1  1  1  1  1  1 -1  1  1  1
  1  1 -1  1  1  1 -1 -1 -1 -1 -1  1 -1  1]


In [11]:
#measuring performance
from sklearn.metrics import accuracy_score

y_preds = perceptron.predict(test_data)
accuracy = accuracy_score(y_preds, test_labels)
print('accuracy:', round(accuracy,2)*100, "%")


accuracy: 100.0 %


#**Tutorial-01 Tasks**


Task 1

In [12]:
# Task 1: Manual Input and Prediction
print("\n--- Manual Prediction ---")
sl = float(input("Enter Sepal Length: "))
sw = float(input("Enter Sepal Width: "))
pl = float(input("Enter Petal Length: "))
pw = float(input("Enter Petal Width: "))

# Reshape input for the model
manual_input = np.array([[sl, sw, pl, pw]])
prediction = perceptron.predict(manual_input)

# Interpret result
result = "Iris-setosa" if prediction[0] == -1 else "Not Iris-setosa"
print(f"The model predicts: {result}")


--- Manual Prediction ---
Enter Sepal Length: 2
Enter Sepal Width: 4
Enter Petal Length: 1
Enter Petal Width: 3
The model predicts: Iris-setosa


In [13]:
from sklearn.linear_model import LogisticRegression

# Task 3: Replace labels with 1 (Setosa) and 0 (Not Setosa)
# Note: It's cleaner to use 1 for the target class
train_labels_binary = np.where(train_labels == -1, 1, 0)
test_labels_binary = np.where(test_labels == -1, 1, 0)

# Task 2: Use Logistic Regression (which uses the Sigmoid function internally)
log_reg = LogisticRegression()
log_reg.fit(train_data, train_labels_binary)

# Performance check
new_preds = log_reg.predict(test_data)
new_accuracy = accuracy_score(new_preds, test_labels_binary)
print(f"New Accuracy with Sigmoid/Logistic: {new_accuracy * 100}%")

New Accuracy with Sigmoid/Logistic: 100.0%
